version: '3'
services:
  dashboard:
    build: ./dashboard
    ports:
      - "4100:4100"
    depends_on:
      - "backend"
    networks:
      - "local"
  backend:
    build: ./server
    volumes:
      - metrics-db:/home/admin/metrics-db
    ports:
      - "3000:3000"
    networks:
      - "local"
networks:
  local:
    driver: bridge
volumes:
  metrics-db:
